@startuml

rectangle {
      usecase "Mostrar Menú" as menu
      usecase "Pedir Comida" as pedido

    }
    actor Restaurante
    actor Cliente
    Restaurante -- menu
    Cliente -- menu
    Cliente - pedido
    Restaurante -- (entregar comida)
@enduml

@startuml
left to right direction
Cliente -- (confirmar pedido)
Cliente -- (cancelar pedido)
(devolver cambio) as devolucion
devolucion .(cancelar pedido) :<<include>>
(confirmar pedido) . devolucion :<<include>>
@enduml

@startuml
left to right direction
(acceder)<|.. (registrarse) : <<extend>>
@enduml

@startuml
(pagar) <|-- (pagar con tarjeta)
(pagar en efectivo)--|> (pagar)

left to right direction
Cliente <|- Cliente_Vip
Cliente -- (reservar vuelo)
Cliente_Vip -- (elige asiento)
@enduml

@startuml
left to right direction
Cliente -- (meter dinero)
Cliente -- (pedir azucar)
Cliente -- (pedir producto)
Cliente -- (cancelar)
(cancelar)..|>(devolver dinero):<<include>>
(pedir producto)..|>(devolver dinero) : <<include>>
@enduml

@startuml
left to right direction
newActor -- (identificarse)
newActor -- (pagar)
newActor -- (elegir mensajero)
newActor -- (confirmar)
(pagar) <|--(pagar con tarjeta)
(pagar) <|-- (pagar con transferencia)
(identificarse)<.. (registrarse): <<extend>>
@enduml

